// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: creator_username.sql

package database

import (
	"context"
)

const getAllFeedsWithCreators = `-- name: GetAllFeedsWithCreators :many
SELECT feeds.name AS feed_name, feeds.url, users.name AS user_name
FROM feeds
JOIN users ON feeds.user_id = users.id
`

type GetAllFeedsWithCreatorsRow struct {
	FeedName string
	Url      string
	UserName string
}

func (q *Queries) GetAllFeedsWithCreators(ctx context.Context) ([]GetAllFeedsWithCreatorsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllFeedsWithCreators)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllFeedsWithCreatorsRow
	for rows.Next() {
		var i GetAllFeedsWithCreatorsRow
		if err := rows.Scan(&i.FeedName, &i.Url, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
